services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/env/.env
    depends_on:
      - backend_db
      - redis
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - backend_db_network
    volumes:
      - ./backend:/app
  backend_db:
    image: postgres:14-alpine
    volumes:
      - backend_db_volume:/var/lib/postgresql/data
    env_file:
      - ./backend/env/.env
    ports:
      - 5433:5432
    networks:
      - backend_db_network
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - backend_db_network

volumes:
  backend_db_volume:

networks:
  backend_db_network:
    driver: bridge
