# Generated by Django 4.1.7 on 2023-02-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(default=200, verbose_name='Height in px')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('original_link', models.BooleanField(default=False, help_text='Can user see the link to an original image?', verbose_name='Link to original image')),
                ('expiring_links', models.BooleanField(default=False, help_text='Can user create expiring links?', verbose_name='Expiring links')),
                ('size', models.ManyToManyField(related_name='tier', to='tiers.size')),
            ],
        ),
    ]
