# Generated by Django 4.1.7 on 2023-02-21 08:35
import os
from django.db import migrations


def fill_superuser_tier_field(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()

    superuser = User.objects.get(username=os.environ.get('DJ_SU_USERNAME'))
    superuser.tier_id = 3
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tier'),
    ]

    operations = [
        migrations.RunPython(fill_superuser_tier_field),
    ]
